admin:
  port: 9991

storage:
  kind: io.l5d.zk
  zkAddrs:
  - host: zook
    port: 2181
  pathPrefix: /dtabs
  sessionTimeoutMs: 10000

namers:
- kind: io.l5d.fs
  rootDir: /io.buoyant/disco

interfaces:
- kind: io.l5d.thriftNameInterpreter
  ip: 0.0.0.0
  port: 4100
- kind: io.l5d.httpController
  ip: 0.0.0.0
  port: 4180